export const t = {
  app: {
    title: "Календар UA WELL",
    adminBadge: "Адмін",
  },
  list: {
    heading: "Календар подій",
    empty: "Подій ще немає.",
    emptyFiltered: "Нічого не знайдено за фільтром.",
    loading: "Завантаження подій…",
    newEvent: "+ Нова подія",
    pastLabel: "Минула подія",
    todayLabel: "Сьогодні",
    tomorrowLabel: "Завтра",
    goingCount: (going: number, capacity: number) =>
      `${going} / ${capacity} йдуть`,
  },
  filters: {
    timeAll: "Усі",
    timeUpcoming: "Майбутні",
    timePast: "Минулі",
    typeAll: "Усі типи",
  },
  detail: {
    backToList: "До списку",
    going: "Іду",
    cancelRsvp: "Скасувати реєстрацію",
    delete: "Видалити подію",
    deleteConfirm: "Видалити подію? Цю дію не можна скасувати.",
    notFound: "Подію не знайдено.",
    republish: "Опублікувати в Telegram",
    republishing: "Публікація…",
    rsvpsHeading: "Хто йде",
    rsvpsEmpty: "Поки що ніхто не зареєструвався.",
    commentsHeading: "Обговорення",
    commentsEmpty: "Поки що тиша. Почніть обговорення першим.",
    commentPlaceholder: "Напишіть коментар…",
    commentSubmit: "Надіслати",
    commentSending: "…",
  },
  admin: {
    title: "Нова подія",
    submit: "Створити подію",
    submitting: "Створення…",
    fields: {
      title: "Назва",
      description: "Опис",
      location: "Місце",
      startsAt: "Початок",
      endsAt: "Кінець",
      capacity: "Кількість місць",
      type: "Тип",
    },
    placeholders: {
      title: "Наприклад: Workshop у Штутгарті",
      description: "Розкажіть про подію кілька речень…",
      location: "Місто, адреса або «Online»",
    },
    types: {
      offline: "🟠 Офлайн",
      online: "🟢 Онлайн",
      trip: "🔵 Подорож",
    },
    errors: {
      endBeforeStart: "Кінець має бути пізніше за початок",
      titleTooShort: "Назва занадто коротка",
    },
  },
  toast: {
    eventFull: "Місць не залишилось",
    eventCreated: "Подію створено",
    eventDeleted: "Подію видалено",
    announceFailed: "Подію створено, але оголошення не надіслано",
    announceSent: "Оголошення надіслано в Telegram",
    rsvpCancelled: "Реєстрацію скасовано",
    rsvpDone: "Ви йдете",
    commentEmpty: "Введіть текст коментаря",
    commentFailed: "Не вдалося надіслати коментар",
  },
  common: {
    loading: "Завантаження…",
    error: "Сталася помилка",
    cancel: "Скасувати",
    confirm: "Підтвердити",
  },
  members: {
    navLink: "Учасники",
    heading: "Учасники Community",
    headingCount: (n: number) => `Учасники Community · ${n}`,
    searchPlaceholder: "Пошук за іменем або username…",
    showAdminsOnly: "Лише адміни",
    sortLabel: "Сортувати:",
    sortActivity: "За активністю",
    sortName: "За іменем",
    sortRecent: "Нещодавно приєдналися",
    empty: "Не знайдено учасників.",
    stats: {
      upcoming: "Майбутні",
      past: "Відвідано",
      comments: "Коментарі",
      cancelled: "Скасовано",
      engagement: "Активність",
    },
    memberSince: (dateLabel: string) => `Учасник з ${dateLabel}`,
    lastActivity: (dateLabel: string) => `Остання активність: ${dateLabel}`,
    noLastActivity: "Поки що без активності",
  },
  profile: {
    headingFallback: "Профіль учасника",
    notFound: "Учасника не знайдено.",
    upcoming: "Майбутні події",
    past: "Минулі події",
    recentComments: "Останні коментарі",
    noUpcoming: "Поки немає майбутніх подій.",
    noPast: "Поки немає відвіданих подій.",
    noComments: "Поки немає коментарів.",
    adminActions: "Дії адміністратора",
    promote: "Зробити адміном",
    demote: "Зняти права адміна",
    promoting: "Збереження…",
    cannotDemoteSelf: "Ви не можете зняти права з себе",
  },
  types: {
    offline: { label: "Офлайн", emoji: "🟠" },
    online: { label: "Онлайн", emoji: "🟢" },
    trip: { label: "Подорож", emoji: "🔵" },
  },
} as const

export type EventType = keyof typeof t.types
